### PR TITLE
cfs registration

### PR DESCRIPTION
**Pull request by strippato**

### CODE REVIEW

**Comment by strippato** [comment]
merge?

**Comment by teopost** [comment]
L'ho gia' mergiato

2015-01-01 14:23 GMT+01:00 strip <notifications@github.com>:

> merge?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UieLinux/coding-for-school-os/pull/7#issuecomment-68486557>
> .
>



-- 
Stefano Teodorani
s.teodorani@gmail.com

**Comment by teopost** [comment]
https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go


2015-01-01 14:38 GMT+01:00 Stefano Teodorani <s.teodorani@gmail.com>:

> L'ho gia' mergiato
>
> 2015-01-01 14:23 GMT+01:00 strip <notifications@github.com>:
>
>> merge?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UieLinux/coding-for-school-os/pull/7#issuecomment-68486557>
>> .
>>
>
>
>
> --
> Stefano Teodorani
> s.teodorani@gmail.com
>



-- 
Stefano Teodorani
s.teodorani@gmail.com

**Comment by teopost** [comment]
Fantastico...

https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go

if name == "boring_wozniak" /* Steve Wozniak is not boring */ { goto begin}

2015-01-01 14:40 GMT+01:00 Stefano Teodorani <s.teodorani@gmail.com>:

>
> https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go
>
>
> 2015-01-01 14:38 GMT+01:00 Stefano Teodorani <s.teodorani@gmail.com>:
>
>> L'ho gia' mergiato
>>
>> 2015-01-01 14:23 GMT+01:00 strip <notifications@github.com>:
>>
>>> merge?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/UieLinux/coding-for-school-os/pull/7#issuecomment-68486557>
>>> .
>>>
>>
>>
>>
>> --
>> Stefano Teodorani
>> s.teodorani@gmail.com
>>
>
>
>
> --
> Stefano Teodorani
> s.teodorani@gmail.com
>



-- 
Stefano Teodorani
s.teodorani@gmail.com

**Comment by teopost** [comment]
Forse ho trovato la traccia da usare.

https://github.com/treyhunner/names/


2015-01-01 14:43 GMT+01:00 Stefano Teodorani <s.teodorani@gmail.com>:

> Fantastico...
>
>
> https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go
>
> if name == "boring_wozniak" /* Steve Wozniak is not boring */ { goto begin}
>
>
> 2015-01-01 14:40 GMT+01:00 Stefano Teodorani <s.teodorani@gmail.com>:
>
>>
>> https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go
>>
>>
>> 2015-01-01 14:38 GMT+01:00 Stefano Teodorani <s.teodorani@gmail.com>:
>>
>>> L'ho gia' mergiato
>>>
>>> 2015-01-01 14:23 GMT+01:00 strip <notifications@github.com>:
>>>
>>>> merge?
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/UieLinux/coding-for-school-os/pull/7#issuecomment-68486557>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> Stefano Teodorani
>>> s.teodorani@gmail.com
>>>
>>
>>
>>
>> --
>> Stefano Teodorani
>> s.teodorani@gmail.com
>>
>
>
>
> --
> Stefano Teodorani
> s.teodorani@gmail.com
>



-- 
Stefano Teodorani
s.teodorani@gmail.com

**Pull request merged**
